name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  TrainModel: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore ReviewPredictor.Trainer/ReviewPredictor.Trainer.csproj
    - name: Build
      run: dotnet build ReviewPredictor.Trainer/ReviewPredictor.Trainer.csproj --configuration Release --no-restore
    - name: Train model
      working-directory: ReviewPredictor.Trainer
      run: dotnet run --project ReviewPredictor.Trainer.csproj
    - name: Upload model.zip
      uses: actions/upload-artifact@v2
      with:
        path: ReviewPredictor.Trainer/model.zip
        
        
  Docker:
    needs: [TrainModel]
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v2
      - name: Download model.zip
        uses: actions/download-artifact@v2
        with:
          path: ReviewPredictor/ReviewPredictor
          
      - name: Publish to Registry
        uses: mr-smithers-excellent/docker-build-push@v3
        with:
          dockerfile: ReviewPredictor/Dockerfile
          directory: ReviewPredictor
          image: aslotte/reviewpredictor
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
